### ISSUE TITLE
Roadmap to Version 1.0.0

### ISSUE THREAD

**Issue by astraloverflow** [style-modules/pack-default#5]
## Meta
...

## Modules
- [ ] Typography
  - *Reference* - https://getbootstrap.com/docs/4.0/content/typography/
  - [ ] Base (`<html>`, `<body>`)
  - [ ] paragraphs
  - [ ] headings
  - [ ] "display" headings
  - [ ] "lead" paragraphs
  - [ ] inline text elements
    - [ ] `<mark>`
    - [ ] `<del>`
    - [ ] `<s>`
    - [ ] `<ins>`
    - [ ] `<u>`
    - [ ] `<small>`
    - [ ] `<strong>`
    - [ ] `<em>`
  - [ ] uppercase/lowercase transformation classes
- [ ] semantics
  - *Reference* - https://developer.mozilla.org/en-US/docs/Web/HTML/Element
  - *Reference* - https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques
  - [ ] block quotes
    - [ ] named source
  - [ ] abbreviations
  - [ ] lists
    - [ ] description list
  - [ ] code
    - [ ] `<code>`
    - [ ] `<pre>`
    - [ ] `<var>`
    - [ ] `<kbd>`
    - [ ] `<samp>`
  - [ ] images
    - [ ] responsive?
    - [ ] thumbnails?
  - [ ] figures
    - [ ] `figcaption`
  - [ ] progress bar
- [ ] tables
  - *Reference* - https://getbootstrap.com/docs/4.0/content/tables/
  - [ ] table headers
  - [ ] striped rows
  - [ ] borders
  - [ ] highlight on hover
  - [ ] compact tables
- [ ] forms
  - *Reference* - https://getbootstrap.com/docs/4.0/components/forms/
- [ ] buttons
  - *Reference* - https://getbootstrap.com/docs/4.0/components/buttons/
- [ ] alerts
  - *Reference* - https://getbootstrap.com/docs/4.0/components/alerts/
- [ ] card
  - *Reference* - https://getbootstrap.com/docs/4.0/components/card/
- [ ] dropdowns
  - *Reference* - https://getbootstrap.com/docs/4.0/components/dropdowns/
- [ ] modal
  - *Reference* - https://getbootstrap.com/docs/4.0/components/modal/
- [ ] navs
  - *Reference* - https://getbootstrap.com/docs/4.0/components/navs/
- [ ] navbars
  - *Reference* - https://getbootstrap.com/docs/4.0/components/navbar/
- [ ] pagination
  - *Reference* - https://getbootstrap.com/docs/4.0/components/pagination/
- [ ] tooltip
  - *Reference* - https://getbootstrap.com/docs/4.0/components/tooltips/
